"""Optional OpenAI text generator for the existing PREFER rewriter pipeline.

This file is only needed when the user does not already have a Gemma/FLAN
callable for ``rewrite_selected_df``. The judge integration itself does not
require summaries to be generated by OpenAI.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import time
from typing import Any, Optional


class OpenAITextGenerator:
    def __init__(
        self,
        *,
        model: Optional[str] = None,
        system_prompt: str = "You are a faithful review summarization component.",
        cache_path: str | Path | None = None,
        max_retries: int = 3,
        retry_base_seconds: float = 2.0,
        timeout_seconds: float = 120.0,
        client: Any = None,
    ) -> None:
        self.model = model or os.environ.get("PREFER_REWRITER_MODEL", "gpt-5.6-luna")
        self.system_prompt = system_prompt
        self.cache_path = None if cache_path is None else Path(cache_path)
        self.max_retries = int(max_retries)
        self.retry_base_seconds = float(retry_base_seconds)
        self.timeout_seconds = float(timeout_seconds)
        self._client = client
        self._cache: dict[str, str] = {}
        if self.cache_path is not None and self.cache_path.exists():
            with self.cache_path.open("r", encoding="utf-8") as handle:
                for line in handle:
                    try:
                        row = json.loads(line)
                        self._cache[str(row["key"])] = str(row["text"])
                    except Exception:
                        continue

    def _get_client(self) -> Any:
        if self._client is not None:
            return self._client
        try:
            from openai import OpenAI
        except (ImportError, AttributeError) as exc:
            raise RuntimeError(
                "Install the OpenAI SDK with `python -m pip install -U openai`."
            ) from exc
        self._client = OpenAI(timeout=self.timeout_seconds)
        return self._client

    def __call__(self, prompt: str) -> str:
        prompt = str(prompt).strip()
        key_payload = json.dumps(
            {"model": self.model, "system": self.system_prompt, "prompt": prompt},
            sort_keys=True,
            ensure_ascii=False,
        )
        key = hashlib.sha256(key_payload.encode("utf-8")).hexdigest()
        if key in self._cache:
            return self._cache[key]

        client = self._get_client()
        last_error: Optional[Exception] = None
        for attempt in range(self.max_retries):
            try:
                response = client.responses.create(
                    model=self.model,
                    input=[
                        {"role": "system", "content": self.system_prompt},
                        {"role": "user", "content": prompt},
                    ],
                    store=False,
                )
                text = str(response.output_text).strip()
                if not text:
                    raise RuntimeError("The rewriter returned empty text.")
                self._cache[key] = text
                if self.cache_path is not None:
                    self.cache_path.parent.mkdir(parents=True, exist_ok=True)
                    with self.cache_path.open("a", encoding="utf-8") as handle:
                        handle.write(json.dumps({"key": key, "text": text}, ensure_ascii=False) + "\n")
                return text
            except Exception as exc:
                last_error = exc
                if attempt + 1 >= self.max_retries:
                    break
                time.sleep(self.retry_base_seconds * (2**attempt))
        raise RuntimeError(f"Rewriter failed after {self.max_retries} attempts.") from last_error
